# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(782, 550)
        Form.setMinimumSize(QtCore.QSize(782, 550))
        Form.setMaximumSize(QtCore.QSize(782, 550))
        self.background = QtWidgets.QFrame(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 805, 570))
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.RightBar = QtWidgets.QTabWidget(self.background)
        self.RightBar.setEnabled(True)
        self.RightBar.setGeometry(QtCore.QRect(560, 0, 225, 551))
        self.RightBar.setObjectName("RightBar")
        self.settings = QtWidgets.QWidget()
        self.settings.setEnabled(True)
        self.settings.setObjectName("settings")
        self.ArdSettingsBox = QtWidgets.QGroupBox(self.settings)
        self.ArdSettingsBox.setGeometry(QtCore.QRect(10, 10, 201, 231))
        self.ArdSettingsBox.setObjectName("ArdSettingsBox")
        self.ArdPortBox = QtWidgets.QGroupBox(self.ArdSettingsBox)
        self.ArdPortBox.setGeometry(QtCore.QRect(10, 20, 181, 61))
        self.ArdPortBox.setObjectName("ArdPortBox")
        self.ArdComPort = QtWidgets.QLabel(self.ArdPortBox)
        self.ArdComPort.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(25)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.ArdComPort.setFont(font)
        self.ArdComPort.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ArdComPort.setFrameShape(QtWidgets.QFrame.Box)
        self.ArdComPort.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ArdComPort.setTextFormat(QtCore.Qt.AutoText)
        self.ArdComPort.setScaledContents(False)
        self.ArdComPort.setWordWrap(False)
        self.ArdComPort.setOpenExternalLinks(False)
        self.ArdComPort.setObjectName("ArdComPort")
        self.ArdComPortSelect = QtWidgets.QToolButton(self.ArdPortBox)
        self.ArdComPortSelect.setGeometry(QtCore.QRect(140, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setKerning(True)
        self.ArdComPortSelect.setFont(font)
        self.ArdComPortSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ArdComPortSelect.setArrowType(QtCore.Qt.NoArrow)
        self.ArdComPortSelect.setObjectName("ArdComPortSelect")
        self.ArdSpeedBox = QtWidgets.QGroupBox(self.ArdSettingsBox)
        self.ArdSpeedBox.setGeometry(QtCore.QRect(10, 90, 181, 61))
        self.ArdSpeedBox.setObjectName("ArdSpeedBox")
        self.ArdSpeed = QtWidgets.QLCDNumber(self.ArdSpeedBox)
        self.ArdSpeed.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.ArdSpeed.setFrameShape(QtWidgets.QFrame.Box)
        self.ArdSpeed.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ArdSpeed.setDigitCount(6)
        self.ArdSpeed.setMode(QtWidgets.QLCDNumber.Dec)
        self.ArdSpeed.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ArdSpeed.setProperty("value", 115200.0)
        self.ArdSpeed.setProperty("intValue", 115200)
        self.ArdSpeed.setObjectName("ArdSpeed")
        self.ArdSpeedSelect = QtWidgets.QToolButton(self.ArdSpeedBox)
        self.ArdSpeedSelect.setGeometry(QtCore.QRect(140, 20, 31, 31))
        self.ArdSpeedSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ArdSpeedSelect.setObjectName("ArdSpeedSelect")
        self.ArdSettings = QtWidgets.QGroupBox(self.ArdSettingsBox)
        self.ArdSettings.setGeometry(QtCore.QRect(10, 160, 181, 61))
        self.ArdSettings.setObjectName("ArdSettings")
        self.ArdDataDispatch = QtWidgets.QCheckBox(self.ArdSettings)
        self.ArdDataDispatch.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.ArdDataDispatch.setTabletTracking(False)
        self.ArdDataDispatch.setChecked(True)
        self.ArdDataDispatch.setObjectName("ArdDataDispatch")
        self.Csv = QtWidgets.QGroupBox(self.settings)
        self.Csv.setGeometry(QtCore.QRect(10, 260, 201, 261))
        self.Csv.setObjectName("Csv")
        self.FileNameBox = QtWidgets.QGroupBox(self.Csv)
        self.FileNameBox.setGeometry(QtCore.QRect(10, 20, 181, 51))
        self.FileNameBox.setObjectName("FileNameBox")
        self.FileName = QtWidgets.QLineEdit(self.FileNameBox)
        self.FileName.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.FileName.setMaxLength(21)
        self.FileName.setObjectName("FileName")
        self.label = QtWidgets.QLabel(self.FileNameBox)
        self.label.setGeometry(QtCore.QRect(140, 20, 31, 21))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.DataRecord = QtWidgets.QGroupBox(self.Csv)
        self.DataRecord.setGeometry(QtCore.QRect(10, 80, 181, 171))
        self.DataRecord.setFlat(False)
        self.DataRecord.setCheckable(True)
        self.DataRecord.setChecked(False)
        self.DataRecord.setObjectName("DataRecord")
        self.HelmetRec = QtWidgets.QCheckBox(self.DataRecord)
        self.HelmetRec.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.HelmetRec.setChecked(True)
        self.HelmetRec.setObjectName("HelmetRec")
        self.LhandRec = QtWidgets.QCheckBox(self.DataRecord)
        self.LhandRec.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.LhandRec.setChecked(True)
        self.LhandRec.setObjectName("LhandRec")
        self.RhandRec = QtWidgets.QCheckBox(self.DataRecord)
        self.RhandRec.setGeometry(QtCore.QRect(100, 50, 71, 21))
        self.RhandRec.setChecked(True)
        self.RhandRec.setObjectName("RhandRec")
        self.LkneeRec = QtWidgets.QCheckBox(self.DataRecord)
        self.LkneeRec.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.LkneeRec.setChecked(True)
        self.LkneeRec.setObjectName("LkneeRec")
        self.RkneeRec = QtWidgets.QCheckBox(self.DataRecord)
        self.RkneeRec.setGeometry(QtCore.QRect(100, 80, 71, 21))
        self.RkneeRec.setChecked(True)
        self.RkneeRec.setObjectName("RkneeRec")
        self.LshinRec = QtWidgets.QCheckBox(self.DataRecord)
        self.LshinRec.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.LshinRec.setChecked(True)
        self.LshinRec.setObjectName("LshinRec")
        self.RshinRec = QtWidgets.QCheckBox(self.DataRecord)
        self.RshinRec.setGeometry(QtCore.QRect(100, 110, 71, 21))
        self.RshinRec.setChecked(True)
        self.RshinRec.setObjectName("RshinRec")
        self.SpeedRec = QtWidgets.QCheckBox(self.DataRecord)
        self.SpeedRec.setGeometry(QtCore.QRect(100, 140, 71, 21))
        self.SpeedRec.setChecked(True)
        self.SpeedRec.setObjectName("SpeedRec")
        self.StatusRec = QtWidgets.QCheckBox(self.DataRecord)
        self.StatusRec.setGeometry(QtCore.QRect(10, 140, 81, 21))
        self.StatusRec.setChecked(True)
        self.StatusRec.setObjectName("StatusRec")
        self.RightBar.addTab(self.settings, "")
        self.SpeedBar = QtWidgets.QGroupBox(self.background)
        self.SpeedBar.setEnabled(True)
        self.SpeedBar.setGeometry(QtCore.QRect(30, 150, 81, 201))
        self.SpeedBar.setObjectName("SpeedBar")
        self.SpeedSlider = QtWidgets.QSlider(self.SpeedBar)
        self.SpeedSlider.setGeometry(QtCore.QRect(20, 20, 22, 141))
        self.SpeedSlider.setMaximum(255)
        self.SpeedSlider.setPageStep(10)
        self.SpeedSlider.setOrientation(QtCore.Qt.Vertical)
        self.SpeedSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.SpeedBox = QtWidgets.QSpinBox(self.SpeedBar)
        self.SpeedBox.setGeometry(QtCore.QRect(10, 170, 61, 22))
        self.SpeedBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SpeedBox.setMaximum(255)
        self.SpeedBox.setObjectName("SpeedBox")
        self.SpeedLock = QtWidgets.QToolButton(self.SpeedBar)
        self.SpeedLock.setGeometry(QtCore.QRect(50, 140, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SpeedLock.setFont(font)
        self.SpeedLock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpeedLock.setIconSize(QtCore.QSize(16, 16))
        self.SpeedLock.setCheckable(False)
        self.SpeedLock.setObjectName("SpeedLock")
        self.AccelerationBar = QtWidgets.QGroupBox(self.background)
        self.AccelerationBar.setGeometry(QtCore.QRect(120, 150, 81, 201))
        self.AccelerationBar.setObjectName("AccelerationBar")
        self.AccelerationSlider = QtWidgets.QSlider(self.AccelerationBar)
        self.AccelerationSlider.setGeometry(QtCore.QRect(20, 20, 22, 141))
        self.AccelerationSlider.setMinimum(0)
        self.AccelerationSlider.setMaximum(5)
        self.AccelerationSlider.setPageStep(1)
        self.AccelerationSlider.setProperty("value", 0)
        self.AccelerationSlider.setOrientation(QtCore.Qt.Vertical)
        self.AccelerationSlider.setInvertedAppearance(False)
        self.AccelerationSlider.setInvertedControls(False)
        self.AccelerationSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.AccelerationSlider.setObjectName("AccelerationSlider")
        self.AccelerationBox = QtWidgets.QSpinBox(self.AccelerationBar)
        self.AccelerationBox.setGeometry(QtCore.QRect(10, 170, 61, 22))
        self.AccelerationBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.AccelerationBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.AccelerationBox.setMaximum(5)
        self.AccelerationBox.setObjectName("AccelerationBox")
        self.AccelerationLock = QtWidgets.QToolButton(self.AccelerationBar)
        self.AccelerationLock.setGeometry(QtCore.QRect(50, 140, 21, 21))
        self.AccelerationLock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AccelerationLock.setCheckable(False)
        self.AccelerationLock.setObjectName("AccelerationLock")
        self.CurrentSpeed = QtWidgets.QGroupBox(self.background)
        self.CurrentSpeed.setGeometry(QtCore.QRect(20, 10, 521, 131))
        self.CurrentSpeed.setObjectName("CurrentSpeed")
        self.Display = QtWidgets.QLCDNumber(self.CurrentSpeed)
        self.Display.setGeometry(QtCore.QRect(10, 20, 500, 100))
        self.Display.setSmallDecimalPoint(True)
        self.Display.setDigitCount(3)
        self.Display.setMode(QtWidgets.QLCDNumber.Dec)
        self.Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Display.setProperty("value", 0.0)
        self.Display.setProperty("intValue", 0)
        self.Display.setObjectName("Display")
        self.Console = QtWidgets.QGroupBox(self.background)
        self.Console.setGeometry(QtCore.QRect(30, 360, 501, 181))
        self.Console.setObjectName("Console")
        self.ConsoleOutput = QtWidgets.QTextBrowser(self.Console)
        self.ConsoleOutput.setEnabled(False)
        self.ConsoleOutput.setGeometry(QtCore.QRect(10, 20, 481, 151))
        self.ConsoleOutput.setStyleSheet("")
        self.ConsoleOutput.setObjectName("ConsoleOutput")
        self.ControlBar = QtWidgets.QGroupBox(self.background)
        self.ControlBar.setEnabled(True)
        self.ControlBar.setGeometry(QtCore.QRect(210, 150, 211, 101))
        self.ControlBar.setObjectName("ControlBar")
        self.StartButton = QtWidgets.QPushButton(self.ControlBar)
        self.StartButton.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setObjectName("StartButton")
        self.StopButton = QtWidgets.QPushButton(self.ControlBar)
        self.StopButton.setEnabled(False)
        self.StopButton.setGeometry(QtCore.QRect(110, 20, 91, 71))
        self.StopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopButton.setObjectName("StopButton")
        self.TrainingBar = QtWidgets.QGroupBox(self.background)
        self.TrainingBar.setGeometry(QtCore.QRect(430, 150, 101, 101))
        self.TrainingBar.setObjectName("TrainingBar")
        self.MoveButton = QtWidgets.QPushButton(self.TrainingBar)
        self.MoveButton.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.MoveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MoveButton.setObjectName("MoveButton")
        self.StayButton = QtWidgets.QPushButton(self.TrainingBar)
        self.StayButton.setEnabled(False)
        self.StayButton.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.StayButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StayButton.setObjectName("StayButton")
        self.ArduinoBar = QtWidgets.QGroupBox(self.background)
        self.ArduinoBar.setGeometry(QtCore.QRect(210, 260, 321, 91))
        self.ArduinoBar.setObjectName("ArduinoBar")
        self.ardControl = QtWidgets.QGroupBox(self.ArduinoBar)
        self.ardControl.setGeometry(QtCore.QRect(10, 20, 201, 61))
        self.ardControl.setObjectName("ardControl")
        self.Connect = QtWidgets.QPushButton(self.ardControl)
        self.Connect.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Connect.setObjectName("Connect")
        self.Disconnect = QtWidgets.QPushButton(self.ardControl)
        self.Disconnect.setEnabled(False)
        self.Disconnect.setGeometry(QtCore.QRect(100, 20, 91, 31))
        self.Disconnect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Disconnect.setObjectName("Disconnect")
        self.StatusBar = QtWidgets.QGroupBox(self.ArduinoBar)
        self.StatusBar.setGeometry(QtCore.QRect(220, 20, 91, 61))
        self.StatusBar.setObjectName("StatusBar")
        self.Status = QtWidgets.QLabel(self.StatusBar)
        self.Status.setGeometry(QtCore.QRect(0, 10, 91, 51))
        self.Status.setStyleSheet("")
        self.Status.setObjectName("Status")

        self.retranslateUi(Form)
        self.RightBar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ArdSettingsBox.setTitle(_translate("Form", "Ардуино"))
        self.ArdPortBox.setTitle(_translate("Form", "COM-Порт"))
        self.ArdComPort.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ArdComPortSelect.setText(_translate("Form", "..."))
        self.ArdSpeedBox.setTitle(_translate("Form", "Скорость"))
        self.ArdSpeed.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ArdSpeed.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ArdSpeedSelect.setText(_translate("Form", "..."))
        self.ArdSettings.setTitle(_translate("Form", "Настройки"))
        self.ArdDataDispatch.setText(_translate("Form", "Отправка данных"))
        self.Csv.setTitle(_translate("Form", "CSV"))
        self.FileNameBox.setTitle(_translate("Form", "Имя файла"))
        self.FileName.setText(_translate("Form", "output"))
        self.label.setText(_translate("Form", ".csv"))
        self.DataRecord.setTitle(_translate("Form", "Запись данных"))
        self.HelmetRec.setText(_translate("Form", "Шлем"))
        self.LhandRec.setText(_translate("Form", "Л. Рука"))
        self.RhandRec.setText(_translate("Form", "П. Рука"))
        self.LkneeRec.setText(_translate("Form", "Л. Колено"))
        self.RkneeRec.setText(_translate("Form", "П. Колено"))
        self.LshinRec.setText(_translate("Form", "Л. Голень"))
        self.RshinRec.setText(_translate("Form", "П. Голень"))
        self.SpeedRec.setText(_translate("Form", "Скорость"))
        self.StatusRec.setText(_translate("Form", "Состояние"))
        self.RightBar.setTabText(self.RightBar.indexOf(self.settings), _translate("Form", "Настройки"))
        self.SpeedBar.setTitle(_translate("Form", "Скорость"))
        self.SpeedLock.setText(_translate("Form", "🔓"))
        self.AccelerationBar.setTitle(_translate("Form", "Ускорение"))
        self.AccelerationLock.setText(_translate("Form", "🔓"))
        self.CurrentSpeed.setTitle(_translate("Form", "Текущая скорость"))
        self.Console.setTitle(_translate("Form", "Консоль"))
        self.ConsoleOutput.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.ControlBar.setTitle(_translate("Form", "Управление"))
        self.StartButton.setText(_translate("Form", "Старт"))
        self.StopButton.setText(_translate("Form", "Стоп"))
        self.TrainingBar.setTitle(_translate("Form", "Обучение"))
        self.MoveButton.setText(_translate("Form", "Движение"))
        self.StayButton.setText(_translate("Form", "Остановка"))
        self.ArduinoBar.setTitle(_translate("Form", "Ардуино"))
        self.ardControl.setTitle(_translate("Form", "Управление"))
        self.Connect.setText(_translate("Form", "Подключить"))
        self.Disconnect.setText(_translate("Form", "Отключить"))
        self.StatusBar.setTitle(_translate("Form", "Состояние "))
        self.Status.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ff0004;\">Отключено</span></p></body></html>"))
